FROM rasa/rasa-sdk:3.6.0

WORKDIR /app

# Copy only actions + requirements
COPY ./rasa/actions/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./rasa/actions /app/actions

EXPOSE 5055

CMD ["start", "--actions", "actions"]